apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rater-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: rater-v1
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 85